server:
  port: 5001
  servlet:
    context-path: /wgcloud-agent
spring:
  application:
    name: wgcloud-agent
#日志文件输出路径
logging:
  file:
    path: ./log

#自定义配置参数
base:
  #wgcloud-server端访问地址
  serverUrl: http://localhost:5000
  #本机ip，不要用localhost或127.0.0.1
  bindIp: 172.26.24.52
  #通信token，请和server端配置的wgToken保持一致
  wgToken: wgcloud

#服务器的ip地址
target.service:
      host: 172.26.24.52
      port: 9888